### ISSUE TITLE
3060  6G 不行

### ISSUE THREAD

**Issue by jasmine889966** [zhaoyun0071/Disco-Diffusion-Local#1]
Traceback (most recent call last):
  File "pic_disco.py", line 704, in run
  File "guided_diffusion\gaussian_diffusion.py", line 900, in ddim_sample_loop_progressive
  File "guided_diffusion\gaussian_diffusion.py", line 674, in ddim_sample
  File "guided_diffusion\respace.py", line 102, in condition_score
  File "guided_diffusion\gaussian_diffusion.py", line 400, in condition_score
  File "guided_diffusion\respace.py", line 128, in __call__
  File "pic_disco.py", line 643, in cond_fn
  File "CLIP\clip\model.py", line 337, in encode_image
    return self.visual(image.type(self.dtype))
  File "torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "CLIP\clip\model.py", line 228, in forward
    x = self.transformer(x)
  File "torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "CLIP\clip\model.py", line 199, in forward
    return self.resblocks(x)
  File "torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "CLIP\clip\model.py", line 187, in forward
    x = x + self.mlp(self.ln_2(x))
  File "torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "CLIP\clip\model.py", line 164, in forward
    return x * torch.sigmoid(1.702 * x)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 3.65 GiB already allocated; 0 bytes free; 3.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

"init_image": null,
	"init_scale": 1000,
    "skip_steps": 10,
	"steps": 100,
	"width": 256,
    "height": 128,
	"n_batches": 1,
	"display_rate":5,
	"batch_name":"mixed",
	"intermediate_saves": 2,

**Comment by zhaoyun0071** [comment]
尝试只选择VITB3，尺寸可以768×512

**Comment by Maomao718** [comment]
我3060 [1280, 720]也不行

**Comment by zhaoyun0071** [comment]
> 我3060 [1280, 720]也不行

6g独显768 512
